In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

In [2]:
df = pd.read_csv('3_dataframes/df_speech_recognition.csv')
df.head()

,Unnamed: 0,file_name,good_exception,audio_recognition
0,0,/home/ubuntu/audio_files/Neal Manahan - negati...,Exception,NaN
1,1,/home/ubuntu/audio_files/Neal Manahan - negati...,Exception,NaN
2,2,/home/ubuntu/audio_files/Neal Manahan - negati...,Exception,NaN
3,3,/home/ubuntu/audio_files/Neal Manahan - negati...,Exception,NaN
4,4,/home/ubuntu/audio_files/Neal Manahan - negati...,Exception,NaN

In [4]:
df['audio_recognition'].value_counts().sum()

323

In [5]:
df.shape

(2898, 4)

In [14]:
pd.options.display.max_rows = 50

In [15]:
df['audio_recognition'].value_counts()

California                                                                                     3
home                                                                                           2
83                                                                                             2
call Connor                                                                                    2
okay                                                                                           2
control                                                                                        2
call Cordy Glenn                                                                               1
turn off alarm                                                                                 1
set alarm for 5                                                                                1
Fairfield Inn Express                                                                          1
the two officers in the line of fire                                                           1
location okay 903                                                                              1
rainbow at Royalton Royalton                                                                   1
what time is it                                                                                1
okay what's the weather look like on my lap right up the stage at the Lapin Boylston Street    1
copyright                                                                                      1
since yesterday                                                                                1
Channel 7 rescue 21 year old acting violent                                                    1
call Target near Palomar College map                                                           1
open WhatsApp                                                                                  1
intercourse                                                                                    1
call Davis Market in Stockton California                                                       1
uok                                                                                            1
Drake net worth                                                                                1
okay coffee dial free laptops on Dell laptop                                                   1
                                                                                              ..
2136                                                                                           1
we're going to                                                                                 1
attorneys in Whitehall                                                                         1
21 Firethorn                                                                                   1
watch your Mike's watch am I to get an open mic watch a mic                                    1
Barney                                                                                         1
what sound is that you turn with a RC car 67437                                                1
earlier                                                                                        1
set alarm at 1 alarm at 1                                                                      1
oh 3 or is that the other agencies                                                             1
49047 to 49047                                                                                 1
call Congress located adjacent to the Copley Square library today the top of the boil          1
793 Boylston Street Dental Cairo                                                               1
108                                                                                            1
turn on flashlight                                                                             1
Call wifey                                                                                     1
call Kali Camaro R1 report Drive I want to keep oil Sinclair between editor and Fairfield      1
call David                                                                                     1
my location                                                                                    1
30 years olds for Harrisonville tan jacket blue jeans                                          1
Popeyes                                                                                        1
do I have anything available response to the JFK Library                                       1
365 nv20                                                                                       1
2141                                                                                           1
broadcast we got an email Drive                                                                1
Name: audio_recognition, Length: 316, dtype: int64

In [26]:
df['audio_recognition'][0]

nan

In [31]:
df['audio_recognition'][5]

nan

In [34]:
for i in range(100):
    print(type(df['audio_recognition'][i]))

<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'str'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'str'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'str'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'str'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'str'>
<class 'float'>
<class 'str'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'str'>
<class 'float'>
<class 'str'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'str'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'str'>
<class 'float'>
<class 'float'>
<class 'str'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'str'>
<class 'float'>
<class 'str'>
<class 'float'>
<class 'float'>

In [21]:
df.dtypes

Unnamed: 0            int64
file_name            object
good_exception       object
audio_recognition    object
dtype: object

In [37]:
df.astype(str)

,Unnamed: 0,file_name,good_exception,audio_recognition
0,0,/home/ubuntu/audio_files/Neal Manahan - negati...,Exception,nan
1,1,/home/ubuntu/audio_files/Neal Manahan - negati...,Exception,nan
2,2,/home/ubuntu/audio_files/Neal Manahan - negati...,Exception,nan
3,3,/home/ubuntu/audio_files/Neal Manahan - negati...,Exception,nan
4,4,/home/ubuntu/audio_files/Neal Manahan - negati...,Exception,nan
5,5,/home/ubuntu/audio_files/Neal Manahan - negati...,Exception,nan
6,6,/home/ubuntu/audio_files/Neal Manahan - negati...,Exception,nan
7,7,/home/ubuntu/audio_files/Neal Manahan - negati...,Exception,nan
8,8,/home/ubuntu/audio_files/Neal Manahan - negati...,Exception,nan
9,9,/home/ubuntu/audio_files/Neal Manahan - negati...,Exception,nan
10,10,/home/ubuntu/audio_files/Neal Manahan - negati...,Exception,nan
11,11,/home/ubuntu/audio_files/Neal Manahan - negati...,Good,3425
12,12,/home/ubuntu/audio_files/Neal Manahan - negati...,Exception,nan
13,13,/home/ubuntu/audio_files/Neal Manahan - negati...,Exception,nan
14,14,/home/ubuntu/audio_files/Neal Manahan - negati...,Exception,nan
15,15,/home/ubuntu/audio_files/Neal Manahan - negati...,Good,phone number for Direct Control of Kendall Street
16,16,/home/ubuntu/audio_files/Neal Manahan - negati...,Exception,nan
17,17,/home/ubuntu/audio_files/Neal Manahan - negati...,Exception,nan
18,18,/home/ubuntu/audio_files/Neal Manahan - negati...,Exception,nan
19,19,/home/ubuntu/audio_files/Neal Manahan - negati...,Exception,nan
20,20,/home/ubuntu/audio_files/Neal Manahan - negati...,Exception,nan
21,21,/home/ubuntu/audio_files/Neal Manahan - negati...,Exception,nan
22,22,/home/ubuntu/audio_files/Neal Manahan - negati...,Exception,nan
23,23,/home/ubuntu/audio_files/Neal Manahan - negati...,Exception,nan
24,24,/home/ubuntu/audio_files/Neal Manahan - negati...,Exception,nan
...,...,...,...,...
2873,2873,['/home/ubuntu/audio_files/Neal Manahan - nega...,Exception,nan
2874,2874,['/home/ubuntu/audio_files/Neal Manahan - nega...,Exception,nan
2875,2875,['/home/ubuntu/audio_files/Neal Manahan - nega...,Exception,nan
2876,2876,['/home/ubuntu/audio_files/Neal Manahan - nega...,Exception,nan
2877,2877,['/home/ubuntu/audio_files/Neal Manahan - nega...,Exception,nan
2878,2878,['/home/ubuntu/audio_files/Neal Manahan - nega...,Exception,nan
2879,2879,['/home/ubuntu/audio_files/Neal Manahan - nega...,Exception,nan
2880,2880,['/home/ubuntu/audio_files/Neal Manahan - nega...,Exception,nan
2881,2881,['/home/ubuntu/audio_files/Neal Manahan - nega...,Exception,nan
2882,2882,['/home/ubuntu/audio_files/Neal Manahan - nega...,Exception,nan
2883,2883,['/home/ubuntu/audio_files/Neal Manahan - nega...,Exception,nan
2884,2884,['/home/ubuntu/audio_files/Neal Manahan - nega...,Exception,nan
2885,2885,['/home/ubuntu/audio_files/Neal Manahan - nega...,Exception,nan
2886,2886,['/home/ubuntu/audio_files/Neal Manahan - nega...,Exception,nan
2887,2887,['/home/ubuntu/audio_files/Neal Manahan - nega...,Exception,nan
2888,2888,['/home/ubuntu/audio_files/Neal Manahan - nega...,Exception,nan
2889,2889,['/home/ubuntu/audio_files/Neal Manahan - nega...,Exception,nan
2890,2890,['/home/ubuntu/audio_files/Neal Manahan - nega...,Exception,nan
2891,2891,['/home/ubuntu/audio_files/Neal Manahan - nega...,Exception,nan
2892,2892,['/home/ubuntu/audio_files/Neal Manahan - nega...,Exception,nan
2893,2893,['/home/ubuntu/audio_files/Neal Manahan - nega...,Exception,nan
2894,2894,['/home/ubuntu/audio_files/Neal Manahan - nega...,Exception,nan
2895,2895,['/home/ubuntu/audio_files/Neal Manahan - nega...,Exception,nan
2896,2896,['/home/ubuntu/audio_files/Neal Manahan - nega...,Exception,nan
2897,2897,['/home/ubuntu/audio_files/Neal Manahan - nega...,Exception,nan

In [40]:
df['audio_recognition'] == 'NaN'

0       False
1       False
2       False
3       False
4       False
5       False
6       False
7       False
8       False
9       False
10      False
11      False
12      False
13      False
14      False
15      False
16      False
17      False
18      False
19      False
20      False
21      False
22      False
23      False
24      False
        ...
2873    False
2874    False
2875    False
2876    False
2877    False
2878    False
2879    False
2880    False
2881    False
2882    False
2883    False
2884    False
2885    False
2886    False
2887    False
2888    False
2889    False
2890    False
2891    False
2892    False
2893    False
2894    False
2895    False
2896    False
2897    False
Name: audio_recognition, Length: 2898, dtype: bool